import { db } from "./db";
import { courses, universities } from "@shared/schema";

async function seedDatabase() {
  console.log("Seeding database...");

  // Seed universities
  const universitiesData = [
    {
      name: "University of Cape Town",
      description: "Leading research university offering computer science and engineering programs with strong industry connections",
      imageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
      website: "https://www.uct.ac.za",
      country: "South Africa",
    },
    {
      name: "Addis Ababa University",
      description: "Ethiopia's premier university with strong IT and engineering departments, pioneering technology education in East Africa",
      imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
      website: "https://www.aau.edu.et",
      country: "Ethiopia",
    },
    {
      name: "University of Nairobi",
      description: "Kenya's top university with innovative technology programs and strong connections to Silicon Savannah",
      imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=300",
      website: "https://www.uonbi.ac.ke",
      country: "Kenya",
    },
  ];

  await db.insert(universities).values(universitiesData).onConflictDoNothing();

  // Seed courses
  const coursesData = [
    {
      title: "Full Stack Web Development",
      description: "Master modern web development with React, Node.js, and MongoDB. This comprehensive course covers both frontend and backend development, teaching you to build scalable web applications from scratch. Learn industry best practices, version control with Git, deployment strategies, and modern development workflows.",
      brief: "Master modern web development with React, Node.js, and MongoDB",
      category: "Programming",
      duration: "12 weeks",
      price: "299.00",
      priceEtb: "2500.00",
      imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      rating: "4.9",
      enrollmentCount: 2340,
      isFeatured: true,
      modules: [
        { title: "Introduction to Web Development", duration: "2 hours" },
        { title: "HTML & CSS Fundamentals", duration: "4 hours" },
        { title: "JavaScript Basics", duration: "6 hours" },
        { title: "React Fundamentals", duration: "8 hours" },
        { title: "Node.js and Express", duration: "6 hours" },
        { title: "Database Design with MongoDB", duration: "4 hours" },
        { title: "Authentication & Security", duration: "3 hours" },
        { title: "Deployment & DevOps", duration: "3 hours" },
      ],
    },
    {
      title: "Data Science & Analytics",
      description: "Learn Python, machine learning, and data visualization to become a data scientist. This course covers statistical analysis, data preprocessing, machine learning algorithms, and data visualization techniques. Work with real-world datasets and build a portfolio of data science projects.",
      brief: "Learn Python, machine learning, and data visualization",
      category: "Data Science",
      duration: "16 weeks",
      price: "399.00",
      priceEtb: "3200.00",
      imageUrl: "https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      rating: "4.8",
      enrollmentCount: 1890,
      isFeatured: true,
      modules: [
        { title: "Python for Data Science", duration: "4 hours" },
        { title: "Statistics and Probability", duration: "5 hours" },
        { title: "Data Preprocessing", duration: "3 hours" },
        { title: "Exploratory Data Analysis", duration: "4 hours" },
        { title: "Machine Learning Fundamentals", duration: "6 hours" },
        { title: "Supervised Learning", duration: "5 hours" },
        { title: "Unsupervised Learning", duration: "4 hours" },
        { title: "Data Visualization", duration: "3 hours" },
        { title: "Deep Learning Basics", duration: "5 hours" },
      ],
    },
    {
      title: "Cybersecurity Fundamentals",
      description: "Protect systems and networks from digital attacks. Learn about network security, ethical hacking, risk assessment, and security protocols. This course covers both theoretical concepts and practical skills needed to secure digital infrastructure.",
      brief: "Protect systems and networks from digital attacks",
      category: "Cybersecurity",
      duration: "10 weeks",
      price: "249.00",
      priceEtb: "2000.00",
      imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      rating: "4.7",
      enrollmentCount: 1234,
      isFeatured: true,
      modules: [
        { title: "Introduction to Cybersecurity", duration: "2 hours" },
        { title: "Network Security", duration: "4 hours" },
        { title: "Cryptography Basics", duration: "3 hours" },
        { title: "Ethical Hacking", duration: "5 hours" },
        { title: "Risk Assessment", duration: "3 hours" },
        { title: "Incident Response", duration: "3 hours" },
        { title: "Security Policies", duration: "2 hours" },
      ],
    },
    {
      title: "Mobile App Development with React Native",
      description: "Build cross-platform mobile applications using React Native. Learn to create native iOS and Android apps with a single codebase, implement navigation, handle device features, and publish to app stores.",
      brief: "Build cross-platform mobile applications using React Native",
      category: "Mobile Development",
      duration: "14 weeks",
      price: "349.00",
      priceEtb: "2800.00",
      imageUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      rating: "4.6",
      enrollmentCount: 987,
      isFeatured: false,
      modules: [
        { title: "React Native Basics", duration: "3 hours" },
        { title: "Navigation and Routing", duration: "4 hours" },
        { title: "State Management", duration: "3 hours" },
        { title: "Native Device Features", duration: "4 hours" },
        { title: "API Integration", duration: "3 hours" },
        { title: "Testing Mobile Apps", duration: "3 hours" },
        { title: "App Store Deployment", duration: "2 hours" },
      ],
    },
    {
      title: "Cloud Computing with AWS",
      description: "Learn Amazon Web Services (AWS) and cloud architecture. Master cloud computing concepts, deployment strategies, scalability, and cost optimization. Prepare for AWS certification while building real-world cloud solutions.",
      brief: "Learn Amazon Web Services (AWS) and cloud architecture",
      category: "Cloud Computing",
      duration: "12 weeks",
      price: "379.00",
      priceEtb: "3000.00",
      imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      rating: "4.8",
      enrollmentCount: 1567,
      isFeatured: false,
      modules: [
        { title: "Cloud Computing Fundamentals", duration: "3 hours" },
        { title: "AWS Core Services", duration: "5 hours" },
        { title: "EC2 and Load Balancing", duration: "4 hours" },
        { title: "Storage and Databases", duration: "4 hours" },
        { title: "Security and IAM", duration: "3 hours" },
        { title: "Monitoring and Optimization", duration: "3 hours" },
        { title: "Serverless Architecture", duration: "3 hours" },
      ],
    },
    {
      title: "DevOps and CI/CD",
      description: "Master DevOps practices and continuous integration/continuous deployment. Learn Docker, Kubernetes, Jenkins, and infrastructure as code. Build automated deployment pipelines and improve software delivery processes.",
      brief: "Master DevOps practices and continuous integration/continuous deployment",
      category: "DevOps",
      duration: "10 weeks",
      price: "329.00",
      priceEtb: "2600.00",
      imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      rating: "4.7",
      enrollmentCount: 876,
      isFeatured: false,
      modules: [
        { title: "DevOps Fundamentals", duration: "2 hours" },
        { title: "Version Control with Git", duration: "3 hours" },
        { title: "Docker Containerization", duration: "4 hours" },
        { title: "Kubernetes Orchestration", duration: "5 hours" },
        { title: "CI/CD with Jenkins", duration: "4 hours" },
        { title: "Infrastructure as Code", duration: "3 hours" },
        { title: "Monitoring and Logging", duration: "3 hours" },
      ],
    },
    {
      title: "Artificial Intelligence & Machine Learning",
      description: "Dive into the world of AI and machine learning with Python. Learn neural networks, deep learning, computer vision, and natural language processing. Build intelligent systems that can learn and adapt.",
      brief: "Dive into the world of AI and machine learning with Python",
      category: "Data Science",
      duration: "18 weeks",
      price: "449.00",
      priceEtb: "3600.00",
      imageUrl: "https://images.unsplash.com/photo-1555255707-c07966088b7b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      rating: "4.9",
      enrollmentCount: 1456,
      isFeatured: true,
      modules: [
        { title: "Introduction to AI", duration: "3 hours" },
        { title: "Machine Learning Fundamentals", duration: "5 hours" },
        { title: "Neural Networks", duration: "6 hours" },
        { title: "Deep Learning", duration: "7 hours" },
        { title: "Computer Vision", duration: "5 hours" },
        { title: "Natural Language Processing", duration: "6 hours" },
        { title: "AI Project Development", duration: "4 hours" },
      ],
    },
    {
      title: "Blockchain Development",
      description: "Learn blockchain technology and cryptocurrency development. Build decentralized applications (DApps) using Ethereum, Solidity, and Web3. Understand smart contracts and blockchain architecture.",
      brief: "Learn blockchain technology and cryptocurrency development",
      category: "Programming",
      duration: "14 weeks",
      price: "399.00",
      priceEtb: "3200.00",
      imageUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      rating: "4.6",
      enrollmentCount: 743,
      isFeatured: false,
      modules: [
        { title: "Blockchain Fundamentals", duration: "4 hours" },
        { title: "Cryptocurrency Basics", duration: "3 hours" },
        { title: "Ethereum Development", duration: "5 hours" },
        { title: "Smart Contracts with Solidity", duration: "6 hours" },
        { title: "Web3 Development", duration: "4 hours" },
        { title: "DApp Development", duration: "5 hours" },
        { title: "Blockchain Security", duration: "3 hours" },
      ],
    },
    {
      title: "UI/UX Design for Developers",
      description: "Master user interface and user experience design principles. Learn design thinking, prototyping, user research, and modern design tools like Figma and Adobe XD.",
      brief: "Master user interface and user experience design principles",
      category: "Design",
      duration: "10 weeks",
      price: "279.00",
      priceEtb: "2250.00",
      imageUrl: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      rating: "4.7",
      enrollmentCount: 1123,
      isFeatured: false,
      modules: [
        { title: "Design Thinking", duration: "3 hours" },
        { title: "User Research", duration: "4 hours" },
        { title: "Wireframing & Prototyping", duration: "4 hours" },
        { title: "Visual Design", duration: "5 hours" },
        { title: "Figma Mastery", duration: "3 hours" },
        { title: "Usability Testing", duration: "3 hours" },
        { title: "Design Systems", duration: "3 hours" },
      ],
    },
    {
      title: "Internet of Things (IoT)",
      description: "Build connected devices and smart systems. Learn Arduino, Raspberry Pi, sensor integration, and IoT protocols. Create projects that connect the physical and digital worlds.",
      brief: "Build connected devices and smart systems",
      category: "Hardware",
      duration: "12 weeks",
      price: "349.00",
      priceEtb: "2800.00",
      imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      rating: "4.5",
      enrollmentCount: 892,
      isFeatured: false,
      modules: [
        { title: "IoT Fundamentals", duration: "3 hours" },
        { title: "Arduino Programming", duration: "4 hours" },
        { title: "Raspberry Pi", duration: "4 hours" },
        { title: "Sensor Integration", duration: "4 hours" },
        { title: "IoT Protocols", duration: "3 hours" },
        { title: "Cloud Integration", duration: "3 hours" },
        { title: "IoT Security", duration: "3 hours" },
      ],
    },
    {
      title: "Game Development with Unity",
      description: "Create engaging games using Unity engine and C#. Learn game design principles, 2D and 3D game development, physics, animations, and publishing to app stores.",
      brief: "Create engaging games using Unity engine and C#",
      category: "Game Development",
      duration: "16 weeks",
      price: "389.00",
      priceEtb: "3100.00",
      imageUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      rating: "4.8",
      enrollmentCount: 1234,
      isFeatured: false,
      modules: [
        { title: "Unity Interface", duration: "3 hours" },
        { title: "C# for Unity", duration: "5 hours" },
        { title: "2D Game Development", duration: "6 hours" },
        { title: "3D Game Development", duration: "7 hours" },
        { title: "Physics & Animation", duration: "4 hours" },
        { title: "Game UI & Audio", duration: "3 hours" },
        { title: "Game Publishing", duration: "2 hours" },
      ],
    },
    {
      title: "Digital Marketing & Analytics",
      description: "Master digital marketing strategies and data analytics. Learn SEO, social media marketing, Google Analytics, email marketing, and conversion optimization.",
      brief: "Master digital marketing strategies and data analytics",
      category: "Marketing",
      duration: "8 weeks",
      price: "229.00",
      priceEtb: "1850.00",
      imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
      rating: "4.6",
      enrollmentCount: 1567,
      isFeatured: false,
      modules: [
        { title: "Digital Marketing Basics", duration: "3 hours" },
        { title: "SEO & Content Marketing", duration: "4 hours" },
        { title: "Social Media Marketing", duration: "4 hours" },
        { title: "Google Analytics", duration: "3 hours" },
        { title: "Email Marketing", duration: "3 hours" },
        { title: "Conversion Optimization", duration: "3 hours" },
      ],
    },
  ];

  await db.insert(courses).values(coursesData).onConflictDoNothing();

  console.log("Database seeded successfully!");
}

// Run the seed function
seedDatabase().catch(console.error);
